version: '3.8'
services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dolibarr
      MYSQL_USER: dolibarr_user
      MYSQL_PASSWORD: dolibarr_password
    volumes:
      - db_data:/var/lib/mysql
  
  dolibarr:
    image: tuxgasy/dolibarr
    restart: always
    ports:
      - "8080:80"
    environment:
      DOLI_DB_HOST: db
      DOLI_DB_USER: dolibarr_user
      DOLI_DB_PASSWORD: dolibarr_password
      DOLI_DB_NAME: dolibarr
    depends_on:
      - db

volumes:
  db_data:
